### PR TITLE
Load prisma.config.ts through c12, so the published CLI can read it on plain Node

### PR DESCRIPTION
**Pull request by wmadden-electric**
## At a glance

An ordinary `prisma.config.ts` — TypeScript, split across two files, using an enum:

```ts
// prisma.config.ts
import { defineConfig } from "@prisma/cli-engine";
import { level } from "./shared";

enum Mode {
  Verbose = "verbose",
}

export default defineConfig({ telemetry: { level, mode: Mode.Verbose } });
```

**Before.** The loader read that file with a plain dynamic `import()`. Here is what Node does with it — on Node 24, the newest release and the one this repo builds with:

```bash
$ node -e 'import("./prisma.config.ts")'
ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX: TypeScript enum is not supported in strip-only mode
```

Take the enum out and it still fails, because Node's TypeScript support will not resolve an extensionless import of a sibling `.ts` file:

```bash
$ node -e 'import("./prisma.config.ts")'
ERR_MODULE_NOT_FOUND: Cannot find module '/…/shared'
```

On Node 22.12 through 22.17 — inside the range we support — TypeScript support is off by default and no config file loads at all: `Unknown file extension ".ts"`.

**After.** Same Node, same files:

```bash
$ node -e 'import("@prisma/cli-engine").then(m => m.loadConfig(process.cwd(), { knownSections: ["telemetry"] })).then(c => console.log(c.sections))'
{ telemetry: { level: 'verbose', mode: 'verbose' } }
```

And a config file can now be named explicitly:

```bash
$ prisma auth whoami --config ../shared/prisma.config.ts
```

## What this changes

1. **The config file is loaded with `c12`** — the library prisma/prisma and prisma/composer both already use for this exact problem. c12 evaluates the TypeScript through `jiti`, so the published binary can read the file without a TypeScript-capable runtime.
2. **The file is read only when the command being run needs it.** It used to be read on every invocation, before the arguments were parsed.
3. **`--config <path>` names a config file to read** instead of the `prisma.config.ts` in the current directory. This one falls out of the second.

## Why it was broken, and who it was broken for

The CLI is built around `prisma.config.ts`. The loader read it with a plain dynamic `import()`, and Node either cannot import a TypeScript file or can import only a narrow subset of one, depending on the version. Development never noticed, because everything here runs under `tsx`. The published binary does not.

Worth being clear about the blast radius: nothing was visibly broken yet. No command family in the CLI declares a config section today, so no shipped command reads a setting out of the file. The loader still ran on every invocation and still could not read TypeScript — the failure was sitting there waiting for the first command that consumed a setting. That command arrives in the slice this unblocks, which is why this was ruled on now.

## Copying c12, and the five options that are ours

The ruling was to copy prisma/prisma and prisma/composer rather than design something equivalent. In practice the call is composer's `loadAppConfig` option for option: an explicit `configFile`, `cwd` set to that file's own directory, and the three lookups it turns off (`rcFile`, `globalRc`, `packageJson`). Both references also check that the file c12 handed back is the file they asked for. We were missing that check; it is in now, using composer's comparison through `realpathSync` rather than prisma/prisma's raw string equality, because the raw comparison fails on Windows for a file c12 did load.

Five options are ours rather than theirs, and all five are there for one reason: the references have a config with a fixed set of known keys, and ours treats **every top-level key as a user-authored section name**. That single difference is what makes c12's defaults unsafe here.

- **`extend: false`.** c12 reads a top-level `extends` as an instruction to merge in another config layer. Left at the default, a user writing `extends: "./base.config.ts"` gets that file's keys merged into the result — even though it carries no `defineConfig` marker, walking straight around the check that exists to stop the loader interpreting an unmarked file. Turned off, `extends` survives into the object as an ordinary key and is reported as an unrecognised section, which is what the closed key set below asks for anyway.
- **`giget: false`.** With merging live, `extends: "http://…"` reaches c12's remote-template fetcher, which downloads and evaluates a tarball. Confirmed against the built package, using a dead local port so nothing left the machine. `extend: false` already makes that unreachable; this keeps it unreachable if merging is ever switched back on.
- **`dotenv: false`.** Already the default. If it ever flipped, loading a config would read a `.env` beside the file and mutate `process.env` — a much larger change in what "load the config" means than anything else here.
- **`envName: false`.** c12 defaults this to `NODE_ENV`, then merges any `$production` or `$env.production` block over the root of the file. Without this a config would mean one thing in a normal shell and another under `NODE_ENV=production`.
- **`omit$Keys: false`.** Already the default, pinned because we depend on it. `$prismaConfig` is the version marker, so stripping `$`-prefixed keys would make every valid config read as unmarked.

Neither reference passes any of these, so every one is a deliberate deviation, argued at the call site. Three of the five are defaults we rely on rather than behaviour we change, which is why `c12` is exact-pinned rather than carried on a caret range — a caret would deliver a change to any of them automatically. The two other dependencies in that block are exact-pinned already.

One further difference: we resolve the path to an absolute one before calling c12. Neither reference has to, because both are handed an absolute path already.

## Closing the set of section names

Saying that every top-level key is a section name only works if something knows which names are valid. Command families — the groups that own `auth`, `telemetry` and so on — already declare the config section they own, and so does any command mounted without a family. That makes the set of valid top-level keys known before a config file is read. With the set closed:

- An unrecognised top-level key in a user's config is reported instead of quietly ignored.
- A section named `extends`, `__proto__`, or any `$`-prefixed name is an error when the CLI is constructed, so it fails in our build rather than in a user's terminal.

**The engine holds this set, not the loader.** That matters because the loader is a `Runtime` member a host supplies: a check on the far side of that seam holds only for as long as every host writes one, and ours already did not — the test harness's own loader ignored the set entirely. The engine now applies the check itself, next to the section validation it already owned, and `LoadedConfig` carries the path it read so the engine can name the file. Composer's `LoadedAppConfig` does the same. The loader no longer knows what a section name is, and with the names gone it takes a plain `configPath?: string`, which is what both references take.

The test that proves it could not have been written before: hand the engine a loader that returns a section the CLI never declared, and the run still fails.

Two keys can never be reported this way, and both are reserved for that reason. c12 deletes `$meta` whatever options it is given — and on a config built by `defineConfig`, which freezes what it returns, that delete throws and the file is refused as unreadable instead. `__proto__` is dropped by defu while c12 merges layers, which refuses to let a config file reach an object's prototype; the rest of the file then loads normally with the key silently gone. Either way the user never gets an unknown-key message.

An unrecognised key fails every command that declares a config section. That is deliberate: a key the CLI cannot account for is a problem with the shape of the file, and per-section isolation covers a section's contents. `docs/architecture/cli-engine-requirements.md` states it. One consequence is worth knowing — the valid set comes from the commands a binary mounts, so a config file's validity depends on the build as well as on the version marker, and only the marker is visible in the file.

## Reading the file only when a command needs it

The config used to be loaded when the Runtime was assembled, before argv was parsed. That ordering is what would have forced `--config` to be pre-scanned out of raw argv, the way prisma/prisma does it. The pre-scan is a consequence of their structure, not a pattern worth copying: `Runtime.config` was read in exactly one place — the check that runs *after* parsing. So the eagerly-loaded value became a function the engine calls when the command declares a config section, and the ordering problem disappeared.

This matters more than it used to. Every run evaluated the config file; with `jiti` behind it, that is no longer cheap. Proven against the real binary: `auth whoami` succeeds with a deliberately broken `prisma.config.ts` sitting in the directory.

## `--config <path>`

Prisma ORM has this flag, so we should have it too. It sits with the other global flags next to `--json` and `--quiet`, and appears in every command's help without further work.

Of the four malformed shapes prisma/prisma rejects, our argument parser already rejected two with a structured usage error. `--config ""` needed a parse function that throws — a shell produces that from `--config "$UNSET_VAR"`. `--config=` needed a real fix: stricli's flag pattern requires at least one character after the `=`, so it does not recognise the bare token as a flag at all and swallows it as a positional argument.

That one shape is caught by scanning raw argv before the parser runs, which is a pre-scan — the same thing rejected above as a way to find `--config`. The difference is what each one costs when it is wrong. Finding `--config`'s *value* by hand means reimplementing the parser's rules and getting a path wrong; recognising one exact token means the token is rejected wherever it appears ahead of a bare `--`, including as another flag's value. That false positive is inherited from prisma/prisma, the token is an odd thing to need as data, and it is now pinned by a test so it stays deliberate.

A file named by `--config` that is not there is an error rather than an empty config: the user said which file to read. Without the flag nothing changes — current directory only, no walking up, and an absent file is an empty config.

## Verification

The test that carries the weight spawns plain `node` with no `tsx`, against a real TypeScript config file, and asserts both halves: a direct `import()` fails in that process, and `loadConfig` returns the sections anyway. Two cases — one with Node's TypeScript support switched off, one with an enum. The same test covers `--config` reaching a file in a sibling directory, and a missing named file producing `CLI.CONFIG_NOT_FOUND`.

Every behaviour claimed here has a test that fails without it, proven by reverting each source change one at a time, rebuilding and re-running: the local and remote `extends` cases, the closed set covering commands mounted without a family, reserved names failing at construction, diagnostics naming the file `--config` asked for, the `--config=` guard, an empty path, a missing named file, unknown-key reporting, the flag plumbing, and loading the config on every run.

371 engine tests, 1016 CLI tests, 97 telemetry tests, type-check and lint all pass, on Linux and on Windows.

## What it costs

One dependency, `c12`, exact-pinned. Eleven packages new to the lockfile, 888 KB. For an installing user the closure is about 2.9 MB unpacked, of which `jiti` is roughly 60 percent and is the part doing the actual work. Nothing in the closure runs an install script. `giget`, c12's remote-template fetcher, installs at 208 KB and is never reached — `giget: false` and `extend: false` both close the only path to it.

Loading a config through `jiti` costs about 33 ms warm and 93 ms cold, and zero for a command that declares no config section, since c12 is imported at the call site rather than at the top of the module.

## Alternatives considered

- **Depend on `jiti` directly and skip c12.** Smaller, and most of c12's discovery is switched off anyway. Rejected: the ruling was to copy the reference repositories, and matching them means someone reading three Prisma CLIs finds one answer instead of three.
- **Declare `typescript` as an optional peer dependency, the way prisma/prisma's config loader does.** Rejected on inspection — `jiti` has no dependencies of its own and carries its own transform. That peer declaration is a house convention across ten unrelated packages in that repo, and composer uses c12 without it.
- **Leave `extends` live, as both references do.** Rejected. It lets an unmarked config file supply sections through the merge, which is the one thing the version marker exists to prevent, and it makes a config file's meaning depend on a network fetch — something a CLI in CI would experience as an unexplained intermittent failure.
- **Pre-scan argv for `--config`'s value.** Rejected — it existed only to work around loading the config eagerly, and loading the config eagerly was itself the thing to fix.

### CODE REVIEW

**Comment by wmadden-electric** [comment]
Closed — opened without being asked. The ruling was already conveyed where it was needed.

File: packages/cli-engine/src/config-loader.ts [hunk 1]
```diff
@@ -98,6 +103,41 @@ function unreadableDiagnostic(path: string, cause: unknown): Diagnostic {
...
+    globalRc: false,
+    packageJson: false,
+    // The one deviation from the references, and it is forced: their
+    // configs have a fixed set of keys, ours says every top-level key
+    // is a section name. c12 reads `extends` as an instruction to merge
+    // another config layer, so with their options a user's section
+    // called `extends` is consumed and disappears — demonstrated by the
+    // test, not assumed.
+    extend: false,
+  });
```
[the remark this answers is not in the document]
Comment (wmadden-electric) [reply packages/cli-engine/src/config-loader.ts:194]: Fixed in f4a5c6c, and you were right that it was reachable. I verified it against the built loader before changing anything: a config with `telemetry: { level: "info" }` and a `$production` block returned `"info"` normally and the overlay's value under `NODE_ENV=production`.

`envName: false` and `omit$Keys: false` are both back. They had been in this file and I removed them a few commits ago while making the c12 call match composer's exactly — that was the error. Composer can leave them out because its config has a fixed set of keys and no `$`-prefixed marker; ours has both. `omit$Keys` matters more than it looks: `$prismaConfig` is our version marker, so setting it true fails eighteen tests, every valid config reading as unmarked.

Tests added for a `$<NODE_ENV>` block, a `$env` block, and the marker surviving, each setting and restoring NODE_ENV. Removing `envName: false` fails both overlay tests.

File: packages/cli-engine/src/config-loader.ts [hunk 2]
```diff
@@ -98,6 +103,41 @@ function unreadableDiagnostic(path: string, cause: unknown): Diagnostic {
...
+  if (result.configFile !== path) {
+    throw new Error(
+      `config loading resolved ${String(result.configFile)} instead of ${path}`,
+    );
```
[the remark this answers is not in the document]
Comment (wmadden-electric) [reply packages/cli-engine/src/config-loader.ts]: Both halves fixed, in two commits.

The path is now resolved to absolute in `requestedPath`, before `existsSync`, before c12, and before the comparison. You were right that this was broken and not only on Windows: `loadConfig("./some/dir", …)` failed outright with `Cannot find module 'some/dir/prisma.config.ts'`, because jiti cannot resolve a relative specifier. The shipped bin passes an absolute `process.cwd()`, so it never bit in practice. Tests cover a relative cwd for discovery, a relative `--config` value, and a diagnostic still reporting an absolute path.

The Windows failure was fixed separately in 8f0d0c1 by comparing `realpathSync` on both sides rather than the raw strings — that is composer's comparison, where I had copied prisma/prisma's. Windows CI is green.

`envName: false` is addressed in the sibling thread.

File: packages/cli-engine/tests/config.test.ts [hunk 3]
```diff
@@ -125,6 +140,105 @@ describe("loadConfig", () => {
...
+export default defineConfig({ toy: { greeting: Level.Verbose } });
+`,
+      [],
+    );
+    expect(probe.directImportError).toBe("ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX");
+    expect(probe.loaded).toEqual({
+      sections: { toy: { greeting: "verbose" } },
+      diagnostics: [],
+    });
+  }, 60_000);
```
[the remark this answers is not in the document]
Comment (wmadden-electric) [reply packages/cli-engine/tests/config.test.ts]: Fixed in f4a5c6c. The assertion is now `expect.any(String)` — the probe records `error.code ?? error.message` and leaves the field absent when nothing throws, so it still requires the direct import to have failed, just not to have failed in one specific way. The `loadConfig` assertions are untouched, so the test still proves the pair: direct import fails, loader succeeds.

The first probe keeps `ERR_UNKNOWN_FILE_EXTENSION`, since it runs with `--no-experimental-strip-types` where that code is stable across our whole supported range.

File: .drive/projects/prisma-cli-v8/specs/s2-overview.md [hunk 4]
```diff
@@ -87,10 +87,20 @@ can overrule before the affected dispatch runs.
...
+  runtime; the shipped binary runs on ordinary Node. Both reference
+  repositories solved this already and identically, so there is nothing
+  to design. `c12` is a dependency, imported dynamically at the call
+  site, invoked as `loadConfig({ name, cwd, configFile? })`, with
+  `typescript` declared as a peer dependency. See
+  `packages/1-framework/3-tooling/config-loader/src/load.ts` in
+  prisma/prisma, and the `cli` and `composer` packages in
+  prisma/composer. Copy the dependency declarations too, not just the
+  call: `c12` evaluates TypeScript through `jiti`, which it declares as
+  a peer, and that is the part that makes it work on plain Node.
```
[the remark this answers is not in the document]
Comment (wmadden-electric) [reply .drive/projects/prisma-cli-v8/specs/s2-overview.md]: Fixed in f4a5c6c. Both documents now state the real contract: `c12@3.3.4` depends on `jiti` directly, so one ordinary `dependencies` entry is all that has to be declared, and its only peer is `magicast`, which is optional.

The wrong sentence was mine — I wrote the ruling from a misreading of prisma/prisma's config-loader manifest, where `"typescript": ">=5.9"` is a house convention applied across about ten unrelated packages rather than anything to do with c12. Composer uses c12 with no such peer. No TypeScript peer claim has been added for `@prisma/cli-engine`, because we do not declare one.

**Review by wmadden — DISMISSED** [review]

File: packages/cli-engine/src/config-loader.ts [hunk 5]
```diff
@@ -99,34 +182,158 @@ function unreadableDiagnostic(path: string, cause: unknown): Diagnostic {
...
+  exported: Record<string, unknown>,
+): Record<string, unknown> {
+  const sections: Record<string, unknown> = {};
+  for (const [key, value] of Object.entries(exported)) {
+    if (key !== MARKER_KEY) {
+      sections[key] = value;
+    }
+  }
+  return sections;
+}
```
[the remark this answers is not in the document]
Comment (wmadden-electric) [reply packages/cli-engine/src/config-loader.ts:220]: Checked this against the built package: `__proto__` never reaches `sectionsOf` as an own property at all. c12 merges its layers with defu, which drops the key rather than let a config file reach an object's prototype, so the whole config object comes back without it and the rest of the file loads normally around it.

So the key cannot be made reportable here. It has been made a reserved section name instead, alongside `$meta`, for the same reason: a section by that name could never be read. `sectionsOf` is now built with `Object.fromEntries` regardless, so a key that ever did survive that far would be an own property rather than a call to `Object.prototype`'s setter.

Pinned by `a top-level '__proto__' never reaches the loader at all` in `config.test.ts`, and by the reserved-name case in `command-families.test.ts`. Fixed in 7f01f0b.

File: docs/architecture/cli-engine-requirements.md [hunk 6]
```diff
@@ -161,33 +161,17 @@ dependency subtrees behind execution-time imports.
...
+
+The set of top-level keys is closed. Every top-level key names a config section, and the recognised names are exactly the sections the mounted commands and command families declare — so an unrecognised key is reported rather than ignored, and a settings block the user wrote in good faith never disappears in silence. Two consequences are worth stating. First, an unrecognised key is a problem with the file's shape rather than with one section's content, so it is a file-level diagnostic and fails every command that declares a config section, while commands that need no config keep working; whether that reach is right, or an unrecognised key should be reported as a warning instead, is not settled by this requirement. Second, the recognised set depends on what a given binary mounts, so a config file's validity is a property of the build as well as of the file format.
```
[the remark this answers is not in the document]
Comment (wmadden-electric) [reply docs/architecture/cli-engine-requirements.md]: Left open deliberately. Whether an unrecognised top-level key should fail every command that declares a config section, or only warn, is a product decision that has not been made yet, and it is with the repository owner now. R10 records the current behaviour and says the reach of that failure is unsettled, rather than writing one of the two answers into an agreed requirement before anyone has chosen it.

This thread should stay open until that decision lands.

[the remark this answers is not in the document]
Comment (wmadden-electric) [reply docs/architecture/cli-engine-requirements.md]: Settled. R10 no longer leaves the alternative open: a top-level key the CLI cannot account for is a problem with the shape of the file, so it fails every command that reads config, and per-section isolation covers a section's contents rather than the file's shape. Behaviour is unchanged — the document now states what the code already did.

Two related points went into the same paragraph: the check runs in the engine rather than the loader, and a config file's validity depends on which commands the binary mounts, of which only the version marker is visible in the file. Fixed in 106a142.

File: packages/cli-engine/src/config-loader.ts [hunk 7]
```diff
@@ -99,34 +154,140 @@ function unreadableDiagnostic(path: string, cause: unknown): Diagnostic {
...
+    // giget downloads and unpacks an `extends` value beginning http://,
+    // https://, gh:, github:, gitlab: or bitbucket:, then evaluates
+    // what it fetched. What a config file means must never depend on a
+    // network fetch. Unreachable while extend is false, and pinned so
+    // the two cannot come apart.
+    //
+    // dotenv reads a .env beside the config file into process.env.
+    // Loading a config must not mutate the process. Falsy by default
+    // today, and pinned because a change of default would turn reading
+    // a file into a side effect on every later env lookup.
```
Comment (wmadden) [inline packages/cli-engine/src/config-loader.ts]: This seems l8ike a stupidly long comment for something not relevant to this library

**Review by wmadden — APPROVED** [review]
One small comment from me, preemptively approved

File: packages/cli-engine/src/config-loader.ts (hunk 7 above)
Comment (wmadden-electric) [reply packages/cli-engine/src/config-loader.ts]: Agreed — thirty-six lines about another library's defaults, inline in a call. The five switched-off behaviours are now a named constant, `EVALUATE_ONE_FILE_ONLY`, with one line each saying what happens without it. The reasoning that was there is in the pull request and in the tests. 60812ae.
